<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-1CCS179" failures="1" tests="4" name="Regression Test" time="77.818" errors="0" timestamp="2022-11-25T10:40:21 IST">
  <testcase classname="com.ds.testLayer.LoginPageTest" name="verifyLoginTest" time="0.031"/>
  <testcase classname="com.ds.testLayer.BuyFunctionality" name="verifyBuyFunctionalityAxis" time="6.346"/>
  <testcase classname="com.ds.testLayer.BuyFunctionality" name="verifyBuyFunctionalityWipro" time="6.948">
    <failure type="java.lang.AssertionError" message="expected [Order Created successfuy] but found [Order Created successfully]">
      <![CDATA[java.lang.AssertionError: expected [Order Created successfuy] but found [Order Created successfully]
at com.ds.testLayer.BuyFunctionality.verifyBuyFunctionalityWipro(BuyFunctionality.java:27)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- verifyBuyFunctionalityWipro -->
  <testcase classname="com.ds.testLayer.TransactionsTest" name="getTransDetails" time="8.053"/>
</testsuite> <!-- Regression Test -->
